import os

FLASK_ENV = os.getenv("FLASK_ENV")
FLASK_SECRET_KEY = os.getenv("FLASK_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
STRIPE_SECRET_API_KEY = os.getenv("STRIPE_SECRET_API_KEY")
